const $=id=>document.getElementById(id);
const filesEl=$("files"),selected=$("selected"),processBtn=$("process"),target=$("target"),customWrap=$("customWrap"),customKb=$("customKb"),widthEl=$("width"),formatEl=$("format"),status=$("status"),results=$("results");
let files=[];
const fmtBytes=n=>n<1024?n+" B":n<1048576?(n/1024).toFixed(1)+" KB":(n/1048576).toFixed(2)+" MB";
const targetBytes=()=>target.value==="custom"?Math.max(20,Number(customKb.value||300))*1024:Number(target.value);
const refreshSelection=()=>{selected.textContent=files.length?files.length+" عکس انتخاب شد — "+fmtBytes(files.reduce((a,f)=>a+f.size,0))+" مجموع":"عکسی انتخاب نشده";processBtn.disabled=!files.length};
filesEl.onchange=()=>{const added=[...filesEl.files].filter(f=>f.type.startsWith("image/"));files=[...files,...added];filesEl.value="";refreshSelection()};
target.onchange=()=>customWrap.classList.toggle("hidden",target.value!=="custom");
function loadImage(file){return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(u);resolve(img)};img.onerror=reject;img.src=u})}
function canvasBlob(img,maxWidth,mime){let w=img.naturalWidth,h=img.naturalHeight;if(maxWidth>0&&w>maxWidth){h=Math.round(h*maxWidth/w);w=maxWidth}const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);return {blob:q=>new Promise(r=>c.toBlob(r,mime,q))}}
async function compress(img,maxWidth,mime,target){const c=canvasBlob(img,maxWidth,mime);let lo=.05,hi=.98,best=null;for(let i=0;i<9;i++){const q=(lo+hi)/2,b=await c.blob(q);if(!b)break;if(b.size>target)hi=q;else{best=b;lo=q}}if(!best)best=await c.blob(mime==="image/png"?1:.05);return best}
function ext(mime){return mime==="image/webp"?"webp":mime==="image/png"?"png":"jpg"} function baseName(name){return name.replace(/\.[^.]+$/,"")}
async function saveFile(blob,name){const cap=window.Capacitor;const fs=cap&&cap.Plugins&&cap.Plugins.Filesystem;if(!fs)return download(blob,name);const bytes=new Uint8Array(await blob.arrayBuffer());let binary="";const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,i+chunk));await fs.writeFile({path:"AxKam/"+name,data:btoa(binary),directory:"DOCUMENTS",recursive:true});return true}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
processBtn.onclick=async()=>{processBtn.disabled=true;status.classList.remove("hidden");const batch=[...files];const total=batch.length;let done=0;for(const file of batch){status.textContent="پردازش "+(done+1)+" از "+total+"…";try{const img=await loadImage(file);const blob=await compress(img,Number(widthEl.value),formatEl.value,targetBytes());const outName=baseName(file.name)+"-compressed."+ext(formatEl.value),url=URL.createObjectURL(blob);const row=document.createElement("article");row.className="result";row.innerHTML='<img src="'+url+'" alt=""><div class="meta"><strong>'+outName+'</strong>قبل: '+fmtBytes(file.size)+'<br>بعد: '+fmtBytes(blob.size)+'<br>کاهش: '+Math.max(0,Math.round((1-blob.size/file.size)*100))+'%</div><button class="download">ذخیره</button>';row.querySelector(".download").onclick=async()=>{try{await saveFile(blob,outName);row.querySelector(".download").textContent="ذخیره شد ✓"}catch(e){console.error(e);row.querySelector(".download").textContent="خطا در ذخیره"}};results.appendChild(row)}catch(e){console.error(e)}done++}status.textContent="انجام شد: "+done+" از "+total+" عکس. فایل‌ها فقط روی دستگاه شما پردازش شدند.";processBtn.disabled=false};